[package]
name = "lens"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.1.0"
eyre = "0.6.11"
indexmap = "2.1.0"
