[workspace]
resolver = "2"
members = [
    "01-trebuchet",
    "02-cube",
    "03-gears",
    "04-scratchcards",
    "05-soilmap",
    "06-race",
    "07-camel",
    "08-wasteland",
    "09-mirage",
    "10-pipemaze",
    "11-galaxies",
    "12-hotsprings",
    "13-mirrors",
]
