[package]
name = "lagoon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.11"
hex = "0.4.3"
itertools = "0.12.0"
ndarray = "0.15.6"
rgb = "0.8.37"
