[package]
name = "crucible"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "1.4.1"
eyre = "0.6.11"
itertools = "0.12.0"
ndarray = "0.15.6"
petgraph = "0.6.4"
